[package]
name = 'tcp-warp'
version = '0.1.0'
authors = ['Alexander Korolev <kilork@yandex.ru>']
edition = '2018'
description = """
tcp-warp description.
"""
homepage = "https://github.com/kilork/tcp-warp"
keywords = []
license = "Unlicense OR MIT"
readme = "README.md"
repository = "https://github.com/kilork/tcp-warp"

[dependencies]
bytes = '0.5'
failure = '0.1'
futures = '0.3'
log = '0.4'

[dependencies.tokio]
version = '0.2'
features = ['full']

[dependencies.tokio-util]
version = '0.2'
features = ['full']
